services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: birdflu
      POSTGRES_PASSWORD: birdflu
      POSTGRES_DB: birdflu_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./seed_data:/app/seed_data
    ports:
      - "5433:5432"

  web:
    build: .
    restart: unless-stopped
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://birdflu:birdflu@db/birdflu_development
      RAILS_ENV: development
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      WCA_OAUTH_CLIENT_SECRET: ${WCA_OAUTH_CLIENT_SECRET}

volumes:
  postgres_data:
